#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

PT_ROOT_DEFAULT="$PROJECT_ROOT/ReasoningEconomicsPT"
ENV_ROOT_DEFAULT="$PROJECT_ROOT/ReasoningEconomicsEnv"

export REPT_ROOT="${REPT_ROOT:-$PT_ROOT_DEFAULT}"
export ENV_ROOT="${ENV_ROOT:-$ENV_ROOT_DEFAULT}"

if [[ -n "${REPT_DATA_ROOT:-}" ]]; then
    DATA_ROOT="$REPT_DATA_ROOT"
elif [[ -n "${REPT_FS_NAME:-}" ]]; then
    DATA_ROOT="/lambda/nfs/${REPT_FS_NAME}/rept"
else
    DATA_ROOT="/lambda/nfs/rept"
fi
export REPT_DATA_ROOT="$DATA_ROOT"

export REPT_PROFILE="${REPT_PROFILE:-p5.4xlarge-single-h100}"
export REPT_MODEL="${REPT_MODEL:-Qwen/Qwen3-14B}"
export REPT_OUTPUT_DIR="${REPT_OUTPUT_DIR:-$REPT_DATA_ROOT/runs/grpo_qwen3_14b_p5_4xlarge}"
export REPT_NUM_EPOCHS="${REPT_NUM_EPOCHS:-1}"
export REPT_NUM_GENERATIONS="${REPT_NUM_GENERATIONS:-4}"
export REPT_BATCH_SIZE="${REPT_BATCH_SIZE:-4}"
export REPT_GRAD_ACCUM="${REPT_GRAD_ACCUM:-1}"
export REPT_TORCH_DTYPE="${REPT_TORCH_DTYPE:-bfloat16}"
export REPT_VLLM_MODE="${REPT_VLLM_MODE:-colocate}"
export REPT_VLLM_TP="${REPT_VLLM_TP:-1}"
export REPT_COLOCATE_TRAIN_PROCS="${REPT_COLOCATE_TRAIN_PROCS:-1}"
export REPT_VLLM_PORT="${REPT_VLLM_PORT:-8001}"
export REPT_VLLM_GROUP_PORT="${REPT_VLLM_GROUP_PORT:-51216}"
export REPT_VLLM_SERVER_HOST="${REPT_VLLM_SERVER_HOST:-127.0.0.1}"
export REPT_VLLM_GPU_UTIL="${REPT_VLLM_GPU_UTIL:-${REPT_VLLM_GPU_MEMORY_UTILIZATION:-0.25}}"
export REPT_VLLM_GPU_MEMORY_UTILIZATION="${REPT_VLLM_GPU_UTIL}"
export REPT_VLLM_MAX_MODEL_LEN="${REPT_VLLM_MAX_MODEL_LEN:-}"
export REPT_GRADIENT_CHECKPOINTING="${REPT_GRADIENT_CHECKPOINTING:-1}"
export REPT_NO_BF16="${REPT_NO_BF16:-0}"
export REPT_ALPHA="${REPT_ALPHA:-1.0}"
export REPT_LOG_EVERY="${REPT_LOG_EVERY:-1}"
export REPT_N_PROMPTS="${REPT_N_PROMPTS:-50}"
export REPT_MAX_COMPLETION_LENGTH="${REPT_MAX_COMPLETION_LENGTH:-2048}"
export REPT_MAX_TOKENS_PER_STEP="${REPT_MAX_TOKENS_PER_STEP:-$REPT_MAX_COMPLETION_LENGTH}"
export REPT_DEFAULT_BUDGET_MODE="${REPT_DEFAULT_BUDGET_MODE:-soft}"
export REPT_REWARD_LOG_PATH="${REPT_REWARD_LOG_PATH:-$REPT_OUTPUT_DIR/reward_log.jsonl}"
export REPT_INSTALL_DEPS_ON_RUN="${REPT_INSTALL_DEPS_ON_RUN:-0}"
export REPT_REQUIREMENTS_FILE="${REPT_REQUIREMENTS_FILE:-$REPT_ROOT/requirements.lambda.txt}"
export PYTORCH_WHEEL_INDEX="${PYTORCH_WHEEL_INDEX:-}"
export REPT_PYTHON_BIN="${REPT_PYTHON_BIN:-auto}"
export REPT_VENV_SYSTEM_SITE_PACKAGES="${REPT_VENV_SYSTEM_SITE_PACKAGES:-auto}"
export REPT_SKIP_TORCH_INSTALL="${REPT_SKIP_TORCH_INSTALL:-auto}"
export REPT_RECREATE_VENV="${REPT_RECREATE_VENV:-0}"

export REPT_SCOUT_OUTPUT="${REPT_SCOUT_OUTPUT:-$REPT_DATA_ROOT/runs/openenv_seed_manifest_qwen3_14b_50.json}"
export REPT_SCOUT_N_SEEDS="${REPT_SCOUT_N_SEEDS:-50}"

export ENV_BASE_URL="${ENV_BASE_URL:-http://127.0.0.1:8010}"
export ENV_PYTHON_BIN="${ENV_PYTHON_BIN:-auto}"
export ENV_VENV="${ENV_VENV:-$ENV_ROOT/.venv-server}"
export ENV_VENV_SYSTEM_SITE_PACKAGES="${ENV_VENV_SYSTEM_SITE_PACKAGES:-0}"
export REASON_BUDGET_NUM_QUESTIONS="${REASON_BUDGET_NUM_QUESTIONS:-10}"
export REASON_BUDGET_HARD_CAP_MODE="${REASON_BUDGET_HARD_CAP_MODE:-0}"
export REASON_BUDGET_SOFT_ALLOW_NEGATIVE_BUDGET="${REASON_BUDGET_SOFT_ALLOW_NEGATIVE_BUDGET:-1}"
export REASON_BUDGET_SOFT_OVERSPEND_PENALTY="${REASON_BUDGET_SOFT_OVERSPEND_PENALTY:-0.25}"
export REASON_BUDGET_BUDGET_RATIO="${REASON_BUDGET_BUDGET_RATIO:-4.0}"
export REASON_BUDGET_TOKENIZER_NAME="${REASON_BUDGET_TOKENIZER_NAME:-$REPT_MODEL}"

require_var() {
    local name="$1"
    if [[ -z "${!name:-}" ]]; then
        echo "[ERROR] $name is required"
        exit 1
    fi
}
